name: Build Container

on: [push]

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          TAG="ghcr.io/lmartinking/duckbot:{{ github.sha }}"
          docker build . --tag ${TAG}
          docker push ${TAG}

